name: lip_reading
channels:
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.1.0=gpu
  - absl-py=0.9.0=py37_0
  - astor=0.8.0=py37_0
  - blas=1.0=mkl
  - blinker=1.4=py37_0
  - ca-certificates=2020.1.1=0
  - cachetools=3.1.1=py_0
  - certifi=2020.4.5.1=py37_0
  - cffi=1.14.0=py37h7a1dbc1_0
  - chardet=3.0.4=py37_1003
  - cmake=3.17.2=h33f27b4_0
  - cryptography=2.9.2=py37h7a1dbc1_0
  - cudatoolkit=10.1.243=h74a9793_0
  - cudnn=7.6.5=cuda10.1_0
  - cycler=0.10.0=py_2
  - dlib=19.19=py37hbe8b3dd_1
  - freetype=2.10.2=hd328e21_0
  - gast=0.2.2=py37_0
  - google-auth=1.14.1=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=py_0
  - grpcio=1.27.2=py37h351948d_0
  - h5py=2.10.0=py37h5e291fa_0
  - hdf5=1.10.4=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=64.2=he025d50_1
  - idna=2.9=py_1
  - imutils=0.5.3=py37_1
  - intel-openmp=2020.1=216
  - jpeg=9d=he774522_0
  - keras-applications=1.0.8=py_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.2.0=py37heaa310e_0
  - libblas=3.8.0=8_h8933c1f_netlib
  - libcblas=3.8.0=8_h8933c1f_netlib
  - libclang=9.0.1=default_hf44288c_0
  - liblapack=3.8.0=8_h8933c1f_netlib
  - liblapacke=3.8.0=8_h8933c1f_netlib
  - libopencv=4.2.0=py37_6
  - libpng=1.6.37=hfe6a214_1
  - libprotobuf=3.11.4=h7bd577a_0
  - libtiff=4.1.0=h885aae3_6
  - libwebp=1.0.2=hfa6e2cd_5
  - lz4-c=1.9.2=h62dcd97_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.1.1=py37_0
  - matplotlib-base=3.2.1=py37h911224e_0
  - mkl=2020.1=216
  - mkl-service=2.3.0=py37hb782905_0
  - mkl_fft=1.0.15=py37h14836fe_0
  - mkl_random=1.1.1=py37h47e9c7a_0
  - msys2-conda-epoch=20160418=1
  - natsort=7.0.1=py_0
  - numpy=1.18.1=py37h93ca92e_0
  - numpy-base=1.18.1=py37hc3f5095_1
  - oauthlib=3.1.0=py_0
  - opencv=4.2.0=py37_6
  - openssl=1.1.1g=he774522_0
  - opt_einsum=3.1.0=py_0
  - pip=20.0.2=py37_3
  - protobuf=3.11.4=py37h33f27b4_0
  - py-opencv=4.2.0=py37h43977f1_6
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_0
  - pyjwt=1.7.1=py37_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyreadline=2.1=py37_1
  - pysocks=1.7.1=py37_0
  - python=3.7.7=h81c818b_4
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - qt=5.12.5=h7ef1ec2_0
  - requests=2.23.0=py37_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.0=py_0
  - scipy=1.4.1=py37h9439919_0
  - setuptools=47.1.1=py37_0
  - six=1.15.0=py_0
  - sqlite=3.31.1=h2a8f88b_1
  - tensorboard=2.2.1=pyh532a8cf_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.1.0=gpu_py37h7db9008_0
  - tensorflow-base=2.1.0=gpu_py37h55f5790_0
  - tensorflow-estimator=2.1.0=pyhd54b08b_0
  - tensorflow-gpu=2.1.0=h0d30ee6_0
  - termcolor=1.1.0=py37_1
  - tornado=6.0.4=py37hfa6e2cd_0
  - urllib3=1.25.8=py37_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_2
  - werkzeug=0.16.1=py_0
  - wheel=0.34.2=py37_0
  - win_inet_pton=1.1.0=py37_0
  - wincertstore=0.2=py37_0
  - wrapt=1.12.1=py37he774522_1
  - xz=5.2.5=h2fa13f4_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.4=h9f78265_3
  - pip:
    - args==0.1.0
    - click==6.7
    - clint==0.5.1
    - floyd-cli==0.11.17
    - keyboard==0.13.5
    - marshmallow==2.21.0
    - pathlib2==2.3.5
    - pytz==2020.1
    - pyyaml==5.3.1
    - raven==6.10.0
    - requests-toolbelt==0.9.1
    - tabulate==0.8.7
prefix: C:\Users\uiyunkim-research\anaconda3\envs\lip_reading

